comfyui_config:
  server_address: 192.168.10.109:8000
  client_id: t2i_client
workflow_config:
  workflow_json_path: /Users/yu/Documents/ComfyUI/workflows/BasicT2I_V13_ADetailer_disabled_separated_environments_re.json
  image_output_path: /Users/yu/Documents/ComfyUI/output
  library_file_path: /Users/yu/Documents/ComfyUI/workflows/library.yaml
  seed_node_id: 164
  batch_size_node_id: 22
  negative_prompt_node_id: 174
  positive_prompt_node_id: 257
  environment_prompt_node_id: 303
  default_prompts:
    base_positive_prompt: "base_prompt" # 各モデルで推奨されているペースプロンプト(masterpieceとか)
    environment_prompt: "environment_prompt" # 環境プロンプト(室内、屋外、昼、夜など)
    positive_prompt: "positive_prompt"
    negative_prompt: "negative_prompt"
    batch_size: 10

scenes:
  # ベースポジティブプロンプト、ポジティブプロンプト、ネガティブプロンプト、環境プロンプト、バッチサイズ全て定義している例
  - name: "sunset_beach" 
    base_positive_prompt: "A beautiful sunset at the beach"
    positive_prompt: "A beautiful sunset at the beach with <tree> trees and vibrant colors."
    negative_prompt: "blurry, low quality"
    environment_prompt: "tropical, warm"
    batch_size: 1
  # デフォルトのプロンプトを使用する例
  - name: "mountain_lake"
    positive_prompt: "A serene mountain lake surrounded by pine trees and clear skies."
    negative_prompt: "overexposed, noisy"
